config/routes.rb
Rails.application.routes.draw do
  
  get 'photos/index'

  get 'photos/create'

  get 'tags/:tag', to: 'welcome#index', as: "tag"
  

  resources :users

  resources :photos do

    member do 
      post :like
      post :unlike
      post :subscription
      post :unsubscription
      post :tag
    end

  end

  resources :comments

  get '/auth/:provider/callback', :to => 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  delete '/auth/signout', to: 'sessions#destroy'

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :content
  belongs_to :photo
  belongs_to :user

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

  belongs_to :user
  belongs_to :friend, :class_name => "User", :foreign_key => "friend_id"
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  has_attached_file :avatar, :styles => { :medium => "500x1200>", :thumb => "200x200>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :comments, :dependent => :destroy
  has_many :commented_users, :through => :comments, :source => :user

  has_many :tagships
  has_many :tags, :through => :tagships

  validates_presence_of :content
  validates_presence_of :avatar_file_name

  belongs_to :user
  has_many :likes
  has_many :subscriptions

  def find_like_by_user(user)
    self.likes.where( :user => user ).first
  end

  def can_user_like?(user)
    find_like_by_user(user).nil?
  end

  def find_subscription_by_user(user)
    self.subscriptions.where( :user => user ).first
  end

  def can_user_subscription?(user)
    find_subscription_by_user(user).nil?
  end

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
 
  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).photos
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  belongs_to :user
  belongs_to :photo
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :tagships, :dependent => :destroy
  has_many :photos, :through => :tagships

  def self.counts
    self.select("name, count(tagships.tag_id) as count").joins(:tagships).group("tagships.tag_id")
  end
end

app/models/tagship.rb
class Tagship < ActiveRecord::Base
  belongs_to :tag
  belongs_to :photo
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :friendships
  has_many :friends, ->{ where( "friendships.status" => "confirmed") }, :through => :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, ->{ where( "friendships.status" => "confirmed") }, :through => :inverse_friendships, :source => "user"

  has_many :comments, :dependent => :destroy
  has_many :photos, :through => :comments

  has_many :photos

  has_many :likes
  has_many :subscriptions

  def self.from_omniauth(auth_hash)
    user = where( :fb_uid => auth_hash[:uid] ).first_or_initialize
    user.name = auth_hash[:info][:name]
    user.email = auth_hash[:info][:email]
    user.fb_token = auth_hash[:credentials][:token]
    user.fb_expires_at = Time.at(auth_hash[:credentials][:expires_at])
    user.save!
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  helper_method :current_user

  protected

  def authenticate_user!
    unless current_user
      redirect_to root_path
    end    
  end

  def current_user
     @current_user = User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!
  
  def create
    @comment = Comment.new(comment_params)
    
    if @comment.user = current_user 
      @comment.save
      redirect_to root_path
    else
      redirect_to root_path
    end  
  end

  def destroy
    @comment = Comment.find(params[:id])
    
    if @comment.user == current_user
      @comment.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :photo_id, :user_id)
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  before_filter :authenticate_user!

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)

    @photo.user = current_user

    if @photo.save
      redirect_to root_path
    else
      flash[:alert] = "請新增照片和描述"
      render :new
    end 
  end
  
  def show
    @photo = Photo.find(params[:id])
  end

  def destroy
    @photo = Photo.find(params[:id])
    
    if @photo.user == current_user
      @photo.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def like
    @photo = Photo.find(params[:id])
    
    if @photo.can_user_like?(current_user)
      @like = @photo.likes.build
      @like.user = current_user
      @like.save!
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def unlike
    @photo = Photo.find(params[:id])
    
    @like = @photo.find_like_by_user(current_user)

    @like.destroy if @like

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end
  
  # def subscription
  #   @photo = Photo.find(params[:id])

  #   if @photo.can_user_subscription?(current_user)
  #     @subscription = @photo.subscriptions.build
  #     @subscription.user = current_user
  #     @subscription.save!
  #   end

  #   redirect_to :back
  # end

  # def unsubscription
  #   @photo = Photo.find(params[:id])

  #   @subscription = @photo.find_subscription_by_user(current_user)

  #   @subscription.destroy if @subscription

  #   redirect_to root_path
  # end

  private

  def photo_params 
    params.require(:photo).permit(:content, :avatar, :user_id, :all_tags)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  def create
    Rails.logger.debug( env["omniauth.auth"] )
    user = User.from_omniauth(auth_hash)

    reset_session
    session[:user_id] = user.id

    flash[:notice]='Login Successfully'
    redirect_to root_path
  end

  def failure
    Rails.logger.debug( env["omniauth.auth"] )

    flash[:alert]='Login failed'
    redirect_to root_path
  end

  def destroy
    reset_session

    flash[:notice]='Logout Successfully'
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 
  def index
    if params[:tag]
      @photos = Photo.tagged_with(params[:tag]).order("id DESC").page(params[:page]).per(15)
    else
      @photos = Photo.order("id DESC").page(params[:page]).per(15)
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper

  def tag_links(tags)
    raw tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
  end

  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/like.js.erb
$("#like-<%= @photo.id %>").hide();
$("#unlike-<%= @photo.id %>").show();

app/views/photos/new.html.erb
<%= image_tag('bg.jpeg', :class => 'bg') %>
  <%= form_for @photo do |f| %>
    
      <div class='wrapper'>
        <%= f.label :content,'content', :class => 'form_label_content' %> <br>
        <%= f.text_area :content, :class => 'form_textarea_content'%>
      </div>

      <div class='wrapper'>
        <%= f.file_field :avatar, :class => 'avatar'%>
      </div>

      <div class='wrapper'>
        <%= f.label :all_tags,'Tags', :class => 'label_tags' %> <br>
        <%= f.text_field :all_tags, placeholder: "Tags separated with comma", :class => 'tags_input' %>
      </div>

      <div class='wrapper'>
        <%= f.submit 'submit', :class => 'submit' %>
      </div>
    
  <% end %>

app/views/photos/show.html.erb
<div class='photopage_wrapper' >
  <div class='wrapper'>
    <%= image_tag(@photo.avatar(:medium), :class => 'photopage_photo') %>

    <div class='photopage_info'>
      <div class='photopage_like'><span><%= @photo.likes.count%></span>Likes</div>
      <%= @photo.user.try(:name) %> 
      <div class='photopage_content'><%= @photo.content %></div> 
      
      Comments:
      <div class='photopage_comment'>
        <% @photo.comments.each do |comment| %>
           <%= link_to comment.user.name, user_path(comment.user) %> 
          <%= comment.content %>
          <br>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/photos/unlike.js.erb
$("#like-<%= @photo.id %>").show();
$("#unlike-<%= @photo.id %>").hide();

app/views/users/show.html.erb
<div class='userpage_name'>
  <%= image_tag('usercover.jpg', :class => 'usercover') %>
  <span><%= @user.name %></span>
</div> 
  <div class='wrapper'>
    <div class="userpage_photo_wrapper">
      <% @user.photos.each do |photo| %>
        <%= image_tag(photo.avatar(:thumb), :class => 'userpage_photo') %>
      <% end %>
    </div>
  </div>

app/views/welcome/index.html.erb
<div class='home_content'>
  <div class='wrapper'>
    <% @photos.each do |photo| %>
      <%= link_to photo.user.try(:name), user_path(photo.user), :class => 'author' %><!-- 自己 -->
      <div class='time'><%= photo.created_at.to_formatted_s(:short) %></div>  <!-- po照片的時間 -->

      <div class='content_wrapper'>
        <div class='content'>
          <%= link_to image_tag(photo.avatar(:medium)), photo_path(photo), :class => 'photo' %>
          <% if current_user == photo.user %>
            <%= link_to "x", photo_path(photo), :method => :delete, :class => 'photo_delete' %>
          <% end %>

            <div class='like_wrapper'>
              <% if photo.can_user_like?(current_user) %>
                <%= link_to image_tag("unlike.png"), like_photo_path(photo), :method => :post %>
              <% else %>
                <%= link_to image_tag("like.png"), unlike_photo_path(photo), :method => :post %>
              <% end %>
            
              <%= photo.likes.count %>
            
              <% photo.likes.each do |a| %>
                <%= link_to a.user.try(:name), user_path(a.user) if a.user %>       <!-- 顯示like的人 -->
              <% end %> 
            </div>

            <div class='description'>  
              <%= photo.content %>                                                  <!-- photo描述 -->
            </div>

            <div class='tag'>
              Tag:<%= tag_links(photo.all_tags) %>                                      <!-- tags -->
            </div>
                        
            <%#= link_to photo.user.likes.count, photo_path(photo) %>         <!-- 自己曾經按like的照片 -->
                     
            <div class='reply_wrapper'>                      
              <% photo.comments.each do |comment| %>
                <%= link_to comment.user.try(:name), user_path(comment.user), :class => 'reply_user' %>
                <div class='reply_content'>
                  <%= comment.content %>                        <!-- 留言的內容 -->
                  <% if current_user == comment.user %>
                    <%= link_to "x", comment_path(comment), :method => :delete, :class => 'reply_del' %>
                  <% end %>
                </div> 
            <br>
              <% end %>
            </div>

              <%= form_for photo.comments.build do |f| %>
                <%= f.text_field :content, placeholder: "Write a comment", :class => 'content_textarea' %> <!-- 要留言的表單 -->
                <%= f.hidden_field :photo_id %>
              <% end %>
          </div>
    <% end %>
      <div class='paginate'><%= paginate @photos %></div> 
      </div>
  </div>
</div>